version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    filter:
      # ignore 'Feedback' PR
      - do: payload
        pull_request:
          title:
            must_exclude:
              regex: ^Feedback$

    validate:
      # Work in progress
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'wip'

      # No empty description
      - do: description
        no_empty:
          enabled: true
          message: Description matter and should not be empty.

      # Some approve
      - do: approvals
        min:
          count: 1
        required:
          assignees: true

  # Git flow
  # Pull request to main only from release and hotfix branches
  - when: pull_request.*
    filter:
      - do: payload
        pull_request:
          baseRef:
            must_include:
              regex: 'main'
          # ignore 'Feedback' PR
          title:
            must_exclude:
              regex: ^Feedback$
    validate:
      - do: headRef
        must_include:
          regex: '^(release|hotfix)\/.+$'
          message: "Create PR to main only from release and hotfix branches"
