/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.tree.kotlin-application-conventions")
}

dependencies {
    implementation(project(":binaryTree"))
}

application {
    // Define the main class for the application.
    mainClass.set("org.tree.app.AppKt")
}
