/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.tree.kotlin-application-conventions")
}

dependencies {
    implementation(project(":binaryTree"))

    implementation("org.neo4j.driver", "neo4j-java-driver", "5.7.0")
}

application {
    // Define the main class for the application.
    mainClass.set("org.tree.app.AppKt")
}
