name: Build project

on:
  push:
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload test report for library
      uses: actions/upload-artifact@v3
      with:
        name: library-test-report
        path: binaryTree/build/reports/tests/test/
        if-no-files-found: ignore
        
    - name: Upload test report for app
      uses: actions/upload-artifact@v3
      with:
        name: app-test-report
        path: app/build/reports/tests/test/
        if-no-files-found: ignore
