name: Build project

on:
  push:
jobs:
  build-gradle-project:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload reports for library
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: library-reports
          path: binaryTree/build/reports/
          if-no-files-found: ignore

      - name: Upload reports for app
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: app-reports
          path: app/build/reports/
          if-no-files-found: ignore
